@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row">
        <table class="table" style="text-align: center">
            <thead>
            <tr>
                <th scope="col" rowspan="3" colspan="3">Khung chương trình Toán 9</th>
                <th scope="col" colspan="2">Trong chương trình trên lớp</th>
                <th scope="col" colspan="8">Ngoài chương trình trên lớp	</th>
            </tr>
            <tr>
                <th scope="col" rowspan="2">SGK</th>
                <th scope="col" rowspan="2">SBT</th>
                <th scope="col" colspan="3">Độ khó tương đương trên lớp		</th>
                <th scope="col" colspan="3">Lò luyện</th>
                <th scope="col" colspan="2">Hệ chuyên	</th>
            </tr>
            <tr>
                <th scope="col">Cô giao</th>
                <th scope="col">Trung tâm học thêm</th>
                <th scope="col">Sách tham khảo mua về</th>
                <th scope="col">Cô giao</th>
                <th scope="col">Trung tâm học thêm</th>
                <th scope="col">Sách tham khảo mua về</th>
                <th scope="col">Lò luyện</th>
                <th scope="col">Cô giao</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <th scope="row" colspan="3">Đại số</th>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <th></th>
                <th scope="row" colspan="2">Chương I §1. Căn bậc hai</th>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <th></th>
                <th></th>
                <th>§2. Căn thức bậc hai và HĐT	</th>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <th></th>
                <th></th>
                <th>§3. Liên hệ giữa phép nhân và phép khai phương	</th>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <th></th>
                <th></th>
                <th>§4. Liên hệ giữa phép chia và phép khai phương	</th>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <th></th>
                <th></th>
                <th>§6. Biến đổi đơn giản biểu thức chứa căn bậc 2	</th>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <th></th>
                <th></th>
                <th>§7. Biến đổi đơn giản biểu thức chứa căn…. (tiếp)	</th>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <th></th>
                <th></th>
                <th>§8. Rút gọn biểu thức chứa căn bậc hai	</th>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <th></th>
                <th></th>
                <th>§9. Căn bậc ba</th>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <th></th>
                <th scope="row" colspan="2">Chương II §1. Nhắc lại, bổ sung các khái niệm về hàm số</th>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <th></th>
                <th></th>
                <th>§2. Hàm số bậc nhất	</th>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <th></th>
                <th></th>
                <th>§3. Đồ thị hàm số y = ax + b (a ≠ 0)	</th>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <th></th>
                <th></th>
                <th>§4. Đường thẳng song song và đường thẳng cắt nhau	</th>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <th></th>
                <th></th>
                <th>§5. Hệ số góc của đường thẳng y = ax + b (a≠ 0)</th>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <th></th>
                <th scope="row" colspan="2">Chương III §1. Phương trình bậc nhất hai ẩn</th>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <th></th>
                <th></th>
                <th>§2. Hệ hai phương trình bậc nhất hai ẩn	</th>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <th></th>
                <th></th>
                <th>§3. Giải hệ phương trình bằng PP thế</th>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <th></th>
                <th></th>
                <th>§4. Giải hệ phương trình bằng PP cộng đại số	</th>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <th></th>
                <th></th>
                <th>§5. Giải bài toán bằng cách lập phương trình		</th>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <th></th>
                <th></th>
                <th>§5. Giải bài toán bằng cách lập phương trình (tiếp)	</th>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <th></th>
                <th scope="row" colspan="2">Chương IV §1. Hàm số y = ax2 (a #0)</th>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <th></th>
                <th></th>
                <th>§2. Đồ thị hàm số y = ax2 (a #0)	</th>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <th></th>
                <th></th>
                <th>§3. Phương trình bậc hai một ẩn số	</th>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <th></th>
                <th></th>
                <th>§4. Công thức nghiệm của phương trình bậc hai		</th>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <th></th>
                <th></th>
                <th>§5. Công thức nghiệm thu gọn		</th>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <th></th>
                <th></th>
                <th>§6. Hệ thức Vi-et và ứng dụng		</th>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <th></th>
                <th></th>
                <th>§7. Phương trình quy về phương trình bậc hai		</th>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <th></th>
                <th></th>
                <th>§8. Giải bài toán bằng cách lập phương trình		</th>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            //Hình học
            <tr>
                <th scope="row" colspan="3">Hình học</th>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <th></th>
                <th scope="row" colspan="2">Chương I §1. Một số hệ thức về đường cao trong tam giác vuông		</th>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <th></th>
                <th></th>
                <th>§1. Một số hệ thức về cạnh và đường cao…. (tiếp)	</th>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <th></th>
                <th></th>
                <th>§2. Tỉ số lượng giác của góc nhọn		</th>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <th></th>
                <th></th>
                <th>§2. Tỉ số lượng giác của góc nhọn (tiếp)	</th>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <th></th>
                <th></th>
                <th>§3. Sử dụng máy tính bỏ túi để tìm tỉ số lượng giác của góc	</th>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <th></th>
                <th></th>
                <th>§4. Một số hệ thức về cạnh và góc trong tam giác vuông	</th>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <th></th>
                <th></th>
                <th>§5. Ứng dụng thực tế các tỉ số lượng giác, thực hành ngoài trời	</th>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <th></th>
                <th scope="row" colspan="2">Chương II §1. Sự xác định của đường tròn.. T/C…</th>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <th></th>
                <th></th>
                <th>§2. Đường kính và dây của đường tròn</th>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <th></th>
                <th></th>
                <th>§3. Liên hệ giữa dây và khoảng cách từ tâm đến dây</th>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <th></th>
                <th></th>
                <th>§4. Vị trí tương đối của đường thẳng và đường tròn</th>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <th></th>
                <th></th>
                <th>§5. Dấu hiệu nhận biết tiếp tuyến của đường tròn</th>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <th></th>
                <th></th>
                <th>§6. Tính chất của hai tiếp tuyên cắt nhau</th>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <th></th>
                <th></th>
                <th>§7. Vị trí tương đối của hai đường tròn</th>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <th></th>
                <th scope="row" colspan="2">Chương III §1. Góc ở tâm.. Số đo cung</th>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <th></th>
                <th></th>
                <th>§2. Liên hệ giữa cung và dây	</th>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <th></th>
                <th></th>
                <th>§3. Góc nội tiếp	</th>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <th></th>
                <th></th>
                <th>§4. Góc tạo bởi tia tiếp tuyến và dây cung</th>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <th></th>
                <th></th>
                <th>§5. Góc có đỉnh ở bên trong hay bên ngoài đường tròn</th>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <th></th>
                <th></th>
                <th>§6. Cung chứa góc</th>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <th></th>
                <th></th>
                <th>§7. Tứ giác nội tiếp	</th>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <th></th>
                <th></th>
                <th>§8. Đường tròn ngoại tiếp. Đường tròn nội tiếp	</th>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <th></th>
                <th></th>
                <th>§9. Độ dài đường tròn, cung tròn	</th>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <th></th>
                <th></th>
                <th>§10. Diện tích hình tròn, hình quạt tròn	</th>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <th></th>
                <th scope="row" colspan="2">Chương IV §1. Hình trụ, diện tích xung quanh và….</th>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <th></th>
                <th></th>
                <th>§2. Hình nón – hình nón cụt. Diện tích….</th>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <th></th>
                <th></th>
                <th>§3. Hình cầu, diện tích mặt cầu và thể tích hình cầu	</th>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
        </table>
    </div>
</div>
@endsection

@section('after-script')

@endsection
